<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="CodeTemplate\FluentValidationTemplate.txt" />
    <None Remove="CodeTemplate\IRepositoryTemplate.txt" />
    <None Remove="CodeTemplate\IServicesTemplate.txt" />
    <None Remove="CodeTemplate\ModelTemplate.txt" />
    <None Remove="CodeTemplate\RepositoryTemplate.txt" />
    <None Remove="CodeTemplate\ServiceTemplate.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="CodeTemplate\FluentValidationTemplate.txt" />
    <EmbeddedResource Include="CodeTemplate\IServicesTemplate.txt" />
    <EmbeddedResource Include="CodeTemplate\IRepositoryTemplate.txt" />
    <EmbeddedResource Include="CodeTemplate\ModelTemplate.txt">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="CodeTemplate\ServiceTemplate.txt" />
    <EmbeddedResource Include="CodeTemplate\RepositoryTemplate.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Dapper.SimpleCRUD" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
    <PackageReference Include="MySql.Data" Version="8.0.33" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql" Version="9.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.12" />
  </ItemGroup>

</Project>
